adminIE/adminIE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from .views import DashView,ajax_upload


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html")),
    path("users/", include("users.urls")),
    path("cmdb/", include("cmdb.urls")),
    path("dash/", DashView.as_view()),
    path("ajax-upload/", ajax_upload),
    path("octopus/", include("octopus.urls")),
]

adminIE/cmdb/urls.py
from django.urls import path, register_converter,re_path,include
from . import views
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

router.register('idc', views.IDCViewSet)
router.register('cabinet', views.CabinetViewSet)
router.register('sysusers', views.SysUsersViewSet)
router.register('server', views.ServerViewSet)
router.register('memory', views.MemoryViewSet)
router.register('disk', views.DiskViewSet)

# router.register('test', views.TreeNodeViewSet)

router.register('assets', views.AssetViewSet)
router.register('servertree', views.TreeNodeViewSet)


app_name="cmdb"
urlpatterns = [
    path('', include(router.urls)),
    path('assets-list/',TemplateView.as_view(template_name='cmdb/asset-list.html'),name='assets'),
    path('idc-list/',TemplateView.as_view(template_name='cmdb/idc.html'),name='idc'),
    
    path('sysusers-list/',TemplateView.as_view(template_name='cmdb/sysusers.html'),name='sysusers'),
    path('server-list/',TemplateView.as_view(template_name='cmdb/server.html'),name='server'),
    path('meminfo-list/',TemplateView.as_view(template_name='cmdb/meminfo.html'),name='meminfo'),
    path('diskinfo-list/',TemplateView.as_view(template_name='cmdb/diskinfo.html'),name='diskinfo'),
    path('assets_temp-list/',views.AssetListView.as_view(),name='assetstemp'),

    # path('test-list/',TemplateView.as_view(template_name='test.html'),),

    path('assets-detail/',views.AssetDetail.as_view(),name='detail'),
    
    path('assets-list-temp/<slug:pk>/',views.AssetDetail_temp.as_view(),name='detail_temp'),
    path('cabinet-list/',TemplateView.as_view(template_name='cmdb/cabinet.html'),name='cabinet'),
    path('servers/',views.ServerListView.as_view())
    
]

adminIE/users/urls.py
from django.urls import path, register_converter,re_path,include
from . import views
from django.views.generic import TemplateView




app_name="users"
urlpatterns = [
    path('login/',views.UserLoginView.as_view(),name="login"),
    path('logout/', views.UserLogoutView.as_view(), name="logout"),
    path('regist/',views.UserRegisterView.as_view(),name="regist"),
    path('api-auth/', include('rest_framework.urls')),
]

adminIE/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div id="main" style="width: 800px;height:400px;"></div>

{%  endblock %}

{%  block script %}

<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    function assetPie(arr) {
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: '上架设备',
                subtext: '在线展示',
                x: 'center'
            },
            tooltip: {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            legend: {
                x: 'center',
                y: 'bottom',
                data: ['服务器', '路由器', '交换机', '防火墙', ]
            },
            toolbox: {
                show: true,
                feature: {
                    mark: {
                        show: true
                    },
                    dataView: {
                        show: true,
                        readOnly: false
                    },
                    magicType: {
                        show: true,
                        type: ['pie', 'funnel']
                    },
                    restore: {
                        show: true
                    },
                    saveAsImage: {
                        show: true
                    }
                }
            },
            calculable: true,
            series: [{

                name: '上架设备',
                type: 'pie',
                radius: [30, 110],
                center: ['75%', '50%'],
                roseType: 'area',
                data: arr

            }]
        };
        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    }

    $(function () {
        $.getJSON(
            '/dash/',
            function (res) {
                assetPie(res)
            }
        )
    })
</script>


{% endblock %}

adminIE/templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>Auto</b>CMDB</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>

    <form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
      <div class="form-group has-feedback">
        <input type="text" name="username" class="form-control" placeholder="Name or Email or Mobile">
        <span class="glyphicon  glyphicon glyphicon-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" name="password" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-6">
                <a href="{% url 'users:regist' %}" class="btn btn-primary btn-block btn-flat">Register</a>
        </div>
        <!-- /.col -->
        <div class="col-xs-6">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

  
    <!-- /.social-auth-links -->

    

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

adminIE/templates/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Registration Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="/"><b>Auto</b>CMDB</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">Register a new membership</p>

    <form action="{% url 'users:regist' %}" method="post">
        {% csrf_token %}
      <div class="form-group has-feedback">
        <input type="text" name="username" class="form-control" placeholder="Username ">
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="email" name="email" class="form-control" placeholder="Email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="text" name="mobile" class="form-control" placeholder="Mobile">
        <span class="glyphicon glyphicon glyphicon-signal form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" name="password" class="form-control" placeholder="Password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
      
        <!-- /.col -->
        <div class="col-xs-12">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

  </div>
  <!-- /.form-box -->
</div>
<!-- /.register-box -->

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

adminIE/templates/test.html
{% extends 'base.html' %}

{% block content %}
<h1>Ajax上传文件</h1>
<form>
    {% csrf_token %}
    <input type="file" />
    <input type="text" name="one" value="FormData_one" />
    <input type="text" name="two" value="FormData_two" />
    <button>Ajax提交</button>
</form>
{% endblock %}
{% block script  %}
<script>
    $(function () {
        $('#ajax_btn').click(function () {
            var fmd_obj = new FormData(); // 实例化一个对象
            // 向对象中添加数据，格式：fmd_obj.append('key','value')
            fmd_obj.append('sub_file_name', document.getElementById('sub_file').files[0]);
            fmd_obj.append('my_list', ['a', 'b']); //每次都可以向这个对象中添加一个数据
            fmd_obj.append('my_key', 'my_value');
            fmd_obj.append('csrfmiddlewaretoken', '{{ csrf_token }}') // 解决认证问题
            fmd_obj.append('data', $("#Ajax_FD_submit").serialize());

            $.ajax({
                url: "/ajax-upload/",
                type: 'POST',
                data: fmd_obj,
                processData: false, // tell jQuery not to process the data
                contentType: false, // tell jQuery not to set contentType
                success: function (arg) {
                    console.log(arg);
                },
            });
            return false; // 最好返回false，因为如果按钮类型是submit,或者是 button 标签，
            // 则表单自己又会以 GET 的方式再提交一次;返回false阻止表单再次提交
        });
    });
</script>

{% endblock  %}