adminIE/adminIE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from .views import DashView,ajax_upload


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html")),
    path("users/", include("users.urls")),
    path("cmdb/", include("cmdb.urls")),
    path("dash/", DashView.as_view()),
    path("ajax-upload/", ajax_upload),
    path("octopus/", include("octopus.urls")),
]

adminIE/cmdb/urls.py
from django.urls import path, register_converter,re_path,include
from . import views
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

router.register('idc', views.IDCViewSet)
router.register('cabinet', views.CabinetViewSet)
router.register('sysusers', views.SysUsersViewSet)
router.register('server', views.ServerViewSet)
router.register('memory', views.MemoryViewSet)
router.register('disk', views.DiskViewSet)

# router.register('test', views.TreeNodeViewSet)

router.register('assets', views.AssetViewSet)
router.register('servertree', views.TreeNodeViewSet)


app_name="cmdb"
urlpatterns = [
    path('', include(router.urls)),
    path('assets-list/',TemplateView.as_view(template_name='cmdb/asset-list.html'),name='assets'),
    path('idc-list/',TemplateView.as_view(template_name='cmdb/idc.html'),name='idc'),
    
    path('sysusers-list/',TemplateView.as_view(template_name='cmdb/sysusers.html'),name='sysusers'),
    path('server-list/',TemplateView.as_view(template_name='cmdb/server.html'),name='server'),
    path('meminfo-list/',TemplateView.as_view(template_name='cmdb/meminfo.html'),name='meminfo'),
    path('diskinfo-list/',TemplateView.as_view(template_name='cmdb/diskinfo.html'),name='diskinfo'),
    path('assets_temp-list/',views.AssetListView.as_view(),name='assetstemp'),

    # path('test-list/',TemplateView.as_view(template_name='test.html'),),

    path('assets-detail/',views.AssetDetail.as_view(),name='detail'),
    
    path('assets-list-temp/<slug:pk>/',views.AssetDetail_temp.as_view(),name='detail_temp'),
    path('cabinet-list/',TemplateView.as_view(template_name='cmdb/cabinet.html'),name='cabinet'),
    path('servers/',views.ServerListView.as_view())
    
]

adminIE/octopus/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from .views import ConnectionView,EexcCommand,asyncDemoView,get_task,ansible_api
app_name="octopus"
urlpatterns = [
    path("connection/",ConnectionView.as_view(),name='connection'),
    path("run/",EexcCommand.as_view(),name='run'),
    path("get_task/",get_task.as_view(),name='get_task'),
    path("async/",asyncDemoView.as_view(),name='asyncdemo'),
    path("ansible_api/",ansible_api.as_view(),name="ansible_api"),


]

adminIE/octopus/models.py
from django.db import models

# Create your models here.

adminIE/octopus/views.py
from .tasks import ansible_run
from celery.result import AsyncResult
from django.shortcuts import render

# Create your views here.
from django.views.generic import View, ListView
from django.http import JsonResponse, HttpResponse
from cmdb.models import Server, Connection, InventoryPool
import subprocess
import os
import pexpect
from .utils.handle_command import HandleCommand, no_secret


class ConnectionView(ListView):
    queryset = Server.objects.filter(connection__user__isnull=False)
    # model=Server
    context_object_name = "server"
    template_name = "octopus/connection.html"

    def post(self, request):
        rerver_id = request.POST.get("server_id")
        server = Server.objects.filter(id=rerver_id).first()
        ip = server.manager_id
        user = server.connection.user
        pwd = server.connection.password
        port = server.connection.port
        shell_comm = "ssh-copy-id  -p {port} {user}@{ip}".format(
            port=port, user=user, ip=ip
        )
        is_conn = no_secret(shell_comm, pwd)
        if is_conn:
            server.connection.authed = True
            server.connection.save()
            return JsonResponse({"status": True})
        else:
            return JsonResponse({"status": False})


class EexcCommand(ListView):
    model = InventoryPool
    template_name = "octopus/run.html"
    context_object_name = "inventorypools"

    def post(self, request):
        command = request.POST.get("command")  # 获取提交命令(标签name)
        from .tasks import task_ansible

        task = task_ansible.delay(command)
        print(task)  # 必须调用delay方法,异步执行
        # print(task.task_id)
        return JsonResponse({"task_id": task.id})
        # return JsonResponse({"task_id": task})


class asyncDemoView(ListView):
    model = InventoryPool
    template_name = "octopus/async_demo.html"
    context_object_name = "async"

    def post(self, request):
        num = request.POST.get("num")
        from .tasks import add

        task = add.delay(int(num))
        return JsonResponse({"task_id": task.id})


class get_task(View):
    def get(self, request):
        task_id = request.GET.get("task_id")
        task_obj = AsyncResult(id=task_id)
        task_json = {
            "id": task_obj.task_id,
            "status": task_obj.status,
            "success": task_obj.successful(),
            "result": task_obj.result,
        }
        print(task_json)
        return JsonResponse(task_json)


class ansible_api(ListView):
    model = InventoryPool
    context_object_name = "InventoryPool"
    template_name = "octopus/run.html"

    def post(self, request):
        inventory = request.POST.get("inv_path")
        remote_user = request.POST.get("remote_user")
        connection = request.POST.get("connection")
        hosts = request.POST.get("hosts")
        module = request.POST.get("module")
        args = request.POST.get("args")
        print(inventory, remote_user, connection, hosts, module, args)
        task = ansible_run.delay(
            inventory=inventory,
            remote_user=remote_user,
            connection=connection,
            hosts=hosts,
            args=args,
            module=module,
        )
        # print(task.id)
        return JsonResponse({"task_id": task.id})


# from multiprocessing import process

# return JsonResponse(ansible_data)


#         task_id = request.GET.get("task_id")

#         task_obj = AsyncResult(id=task_id)  # 得到task对象
#         print(task_obj)
#         #  获取数据，返回yemian
#         task_json = {
#             "id": task_obj.id,
#             "status": task_obj.status,
#             "success": task_obj.successful(),
#             "result": task_obj.result,
#         }
#         return JsonResponse(task_json)


# class EexcCommand(View):
# def get(self, request):
#     Inventory = InventoryPool.objects.all()
#     return render(request, "octopus/run.html", { "Inventory": Inventory })


# class ConnectionView(View):
#     def get(self, request):
#         conninfo = Server.objects.all()
#         return render(request, "octopus/connection.html", {"connection": conninfo})

adminIE/templates/octopus/async_demo.html
{% extends 'base.html' %}


{% block content %}
内容
<div class="row">
    <div class=" col-md-6 col-md-offset-3">
        <input type="text" id="num">
        <span>
            <button id="btn" class="btn btn-success">发送</button>
        </span>

    </div>


</div>
<div class="row">
    <div class=" col-md-6 col-md-offset-3">
        <span>
            <button id="getTask" class="btn btn-success">结果展示</button>
        </span>
        <p id="task"></p>
    </div>


</div>

{% endblock %}

{% block script %}
<script>
        var  task_id=''
       
        $("#btn").on("click", function () {
            // let num = $(this).parent().siblings().first.val
            let num = document.getElementById("num").value
            $.ajax({
                url: "{% url 'octopus:asyncdemo' %}",
                type: "POST",
                data: {
                    "num": num,
                    "csrfmiddlewaretoken": '{{ csrf_token }}',
                },
                dataType: "json",
                success: function (res) {
                    this.task_id = res.task_id

                    alert(this.task_id)

                }
            });
        });
        $("#getTask").on("click", function () {
            // let num = $(this).parent().siblings().first.val
            // let num = document.getElementById("num").value
            $.ajax({
                url: "/octopus/get_task/?task_id=${task_id}",
                type: "GET",
                data: {
                    // "task_id": task_id,
                    "csrfmiddlewaretoken": '{{ csrf_token }}',
                },
                dataType: "json",
                success: function (res) {
                    
                    $("#task").append(

                            res.id
                    )

                }
            });
        })


</script>
{% endblock %}

adminIE/templates/octopus/connection.html
{% extends 'base.html' %}

{% block content %}
<div class="box">
    <div class="box-header">
        <h3 class="box-title">公钥推送</h3>

        <div class="box-tools">
            <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body table-responsive  no-padding">
        <table class="table table-hover">
            <tbody>
                <tr>
                    <th>ID</th>
                    <th>服务器主机名</th>
                    <th>用户</th>
                    <th>服务器IP</th>
                    <th>sshd监听端口</th>
                    <th>认证</th>
                    <th>点击推送公钥</th>
                </tr>
                {% for item in server %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.host_name }}</td>
                    <td>
                        <option>{{ item.connection.user }}</option>
                    </td>
                    <td>{{ item.manager_id }}</td>
                    <td> {{ item.connection.port }}</td>
                    <td>
                        {% if item.connection.authed %}
                        <span class="label label-success"> {{ item.connection.authed }}</span>
                        {% else %}
                        <span class="label label-warning"> {{ item.connection.authed }}</span>
                        {% endif %}
                    </td>
                    <td><span class="label label-primary Pushkey">推送公钥</span></td>
                    <!-- <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td> -->
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
</div>
{% endblock %}
{%  block script %}
<script>
    $(".Pushkey").on("click", function () {
        let id = $(this).parent().siblings().first().text();
        
        $.ajax({
            url: "{% url 'octopus:connection' %}",
            type: "POST",
            data: {
                "server_id": id,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            dataType:"json",
            success: function (res) {
                if (res.status) {
                    alert("操作成功！")
                } else {
                    alert("操作失败！")
                }
            }
        })


    })
</script>

{% endblock %}

adminIE/templates/octopus/run.html
{% extends 'base.html' %}



{% block content %}
<section class="content">
    <div class="row">
        <div class="col-md-3">


            <!-- /. box -->
            <div class="box box-solid">
                {% for inventorypool in inventorypools %}




                <div class="form-group">
                    <label>{{ inventorypool.group }}</label>
                    <select multiple="" class="form-control">
                        {%  for item in inventorypool.server.all  %}
                        <option>{{ item.manager_id }}</option>
                        {% endfor %}
                    </select>
                </div>


                {% endfor %}
                <form role="form">
                    <!-- text input -->

                    <!-- textarea -->

                    <div class="form-group has-warning">
                        <label class="control-label" for="inv_path"><i class="fa fa-bell-o"></i>主机清单文件路径</label>
                        <input type="text" class="form-control" id="inv_path" placeholder="Enter ...">
                        <span class="help-block"></span>
                    </div>
                    <div class="form-group has-error">
                        <label class="control-label" for="args"><i class="fa fa-times-circle-o"></i>
                            shell命令</label>
                        <input type="text" class="form-control" id="args" placeholder="Enter ...">
                        <span class="help-block"></span>
                    </div>
                    <div class="form-group">
                        <label>connection</label>
                        <select class="form-control" id="connection">
                            <option>smart</option>
                            <option>local</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>remote_user</label>
                        <select class="form-control" id="remote_user">
                            <option>root</option>
                            <option>stus</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>module</label>
                        <select class="form-control" id="module">
                            <option>shell</option>
                            <option>ping</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>hosts</label>
                        <select class="form-control" id="hosts">
                            <option>NB</option>
                            <option>db_server</option>
                        </select>
                    </div>
                    <a href="#" class="btn btn-primary btn-block margin-bottom ansiblekey">执行Ansible命令</a>
                </form>
            </div>


        </div>
        <!-- /.col -->
        <div class="col-md-9">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">执行Ansible命令</h3>

                    <div class="box-tools pull-right">
                        <div class="has-feedback">
                            <input type="text" class="form-control input-sm" placeholder="Search Mail">
                            <span class="glyphicon glyphicon-search form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="box-footer"></div>

                    <!-- {% csrf_token %} -->
                    <h4>执行命令</h4>
                    <div class="input-group">

                        <input type="text" id="command" name="command" placeholder="ansible all -m shell -a  'ls /tmp'"
                            class="form-control">
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-success btn-flat Pushkey">Send</button>
                        </span>
                    </div>

                    <div class="box-footer"></div>
                    <h3 class="box-title">执行Ansible命令</h3>
                    <p id="result"></p>

                </div>
            </div>
        </div>

    </div>

</section>
{% endblock %}

{%  block script %}
<script>
    $(".Pushkey").on("click", function () {
        //  取得的值
        let command = document.getElementById("command").value
        if (!command) {
            return false
        }

        $.ajax({
            url: "{% url 'octopus:run' %}",
            type: "POST",
            data: {
                "command": command,
                "csrfmiddlewaretoken": '{{ csrf_token }}',
            },
            dataType: "json",
            success: function (res) {

                let task_id = res.task_id;
                // let task= res.task_id;
                // console.log(task_id)
                // handleTask(task_id);

                // Result_Task(this.task_id)
                // this.result = res.result.msg
                // this.status= res.result.status
                // $("#result").text(this.result)
            }
        });
    })

    $(".ansiblekey").on("click", function () {

        let inv_path = document.getElementById("inv_path").value
        let args = document.getElementById("args").value
        let connection = $("#connection option:selected").val()
        let remote_user = $("#remote_user option:selected").val()
        let module = $("#module option:selected").val()
        let hosts = $("#hosts option:selected").val()
        //  取得的值
        // alert(connection)
        if (!inv_path ) {
            return false
        }
        $.ajax({
            url: "{% url 'octopus:ansible_api' %}",
            type: "POST",
            data: {
                "hosts": hosts,
                "inv_path": inv_path,
                "args": args,
                "remote_user": remote_user,
                "module": module,
                "connection": connection,
                "csrfmiddlewaretoken": '{{ csrf_token }}',
            },
            dataType: "json",
            success: function (res) {

                let task_id = res.task_id;
                // alert(task_id)
                handleTask(task_id)
                // let task= res.task_id;
                // console.log(task_id)

            }
        });
    })
</script>
{% endblock %}