adminIE/adminIE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from .views import DashView,ajax_upload


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html")),
    path("users/", include("users.urls")),
    path("cmdb/", include("cmdb.urls")),
    path("dash/", DashView.as_view()),
    path("ajax-upload/", ajax_upload),
    path("octopus/", include("octopus.urls")),
]

adminIE/cmdb/urls.py
from django.urls import path, register_converter,re_path,include
from . import views
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

router.register('idc', views.IDCViewSet)
router.register('cabinet', views.CabinetViewSet)
router.register('sysusers', views.SysUsersViewSet)
router.register('server', views.ServerViewSet)
router.register('memory', views.MemoryViewSet)
router.register('disk', views.DiskViewSet)

# router.register('test', views.TreeNodeViewSet)

router.register('assets', views.AssetViewSet)
router.register('servertree', views.TreeNodeViewSet)


app_name="cmdb"
urlpatterns = [
    path('', include(router.urls)),
    path('assets-list/',TemplateView.as_view(template_name='cmdb/asset-list.html'),name='assets'),
    path('idc-list/',TemplateView.as_view(template_name='cmdb/idc.html'),name='idc'),
    
    path('sysusers-list/',TemplateView.as_view(template_name='cmdb/sysusers.html'),name='sysusers'),
    path('server-list/',TemplateView.as_view(template_name='cmdb/server.html'),name='server'),
    path('meminfo-list/',TemplateView.as_view(template_name='cmdb/meminfo.html'),name='meminfo'),
    path('diskinfo-list/',TemplateView.as_view(template_name='cmdb/diskinfo.html'),name='diskinfo'),
    path('assets_temp-list/',views.AssetListView.as_view(),name='assetstemp'),

    # path('test-list/',TemplateView.as_view(template_name='test.html'),),

    path('assets-detail/',views.AssetDetail.as_view(),name='detail'),
    
    path('assets-list-temp/<slug:pk>/',views.AssetDetail_temp.as_view(),name='detail_temp'),
    path('cabinet-list/',TemplateView.as_view(template_name='cmdb/cabinet.html'),name='cabinet'),
    path('servers/',views.ServerListView.as_view())
    
]

adminIE/Cabinet/models.py
from django.db import models

# Create your models here.

adminIE/cmdb/models.py
from django.db import models
from django.utils import timezone


class TreeNode(models.Model):
    node_name = models.CharField("节点名称", max_length=128)
    node_upstream = models.ForeignKey(
        "self",
        verbose_name="上级节点",
        related_name="sub_node",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "服务树节点表"
        verbose_name_plural = verbose_name
        db_table = "tree_node"

    def __str__(self):
        up_node = self.node_upstream.node_name if self.node_upstream else "根节点"
        return f"{up_node}-->{self.node_name}"


class Tag(models.Model):
    name = models.CharField("标签", max_length=64)
    latest_date = models.DateField(
        verbose_name="更新时间", default=timezone.now, null=True, blank=True
    )
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        verbose_name = "标签信息表"
        verbose_name_plural = verbose_name
        db_table = "tag"

    def __str__(self):
        return self.name


class IDC(models.Model):
    """
    IDC 机房信息
    """

    name = models.CharField("机房名称", max_length=128)
    addr = models.CharField("地址", max_length=256)
    phone = models.CharField("联系电话", max_length=11)
    latest_date = models.DateField(
        verbose_name="更新时间", default=timezone.now, null=True, blank=True
    )
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        verbose_name = "机房信息表"
        verbose_name_plural = verbose_name
        db_table = "idc"

    def __str__(self):
        return self.name


class SysUsers(models.Model):
    users_choices = (("1", "超级用户"), ("2", "sudo用户"), ("3", "普通用户"))
    name = models.CharField("用户名", max_length=16)
    user_type = models.CharField(
        "用户类型", choices=users_choices, default="3", max_length=1
    )

    class Mate:
        verbose_name = "用户表"
        verbose_name_plural = verbose_name
        db_table = "sysusers"

    def __str__(self):
        return self.name


class Cabinet(models.Model):
    """
    机柜信息
    """

    name = models.CharField("机柜编号", max_length=128)
    idc = models.ForeignKey(
        "idc", related_name="cabinet", verbose_name="所属机房", on_delete=models.CASCADE
    )
    latest_date = models.DateField(
        verbose_name="更新时间", default=timezone.now, null=True, blank=True
    )
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        verbose_name = "机柜信息表"
        verbose_name_plural = verbose_name
        db_table = "cabinet"

    def __str__(self):
        return self.name


class Asset(models.Model):
    """
    资产信息表，所有资产公共信息（交换机，服务器，防火墙等）
    """

    device_type_choices = (("1", "服务器"), ("2", "路由器"),
                           ("3", "交换机"), ("4", "防火墙"))
    device_status_choices = (("1", "上架"), ("2", "在线"),
                             ("3", "离线"), ("4", "下架"))

    device_type_id = models.CharField(
        choices=device_type_choices, max_length=1, default="1", help_text="设备类型"
    )
    device_status_id = models.CharField(
        choices=device_status_choices, max_length=1, default="1", help_text="设备状态"
    )
    cabinet = models.ForeignKey(
        "cabinet", verbose_name="所属机柜", related_name="asset", on_delete=models.CASCADE
    )
    # cabinet = models.CharField("机柜", max_length=128)
    node = models.ForeignKey(
        "TreeNode", verbose_name="节点", related_name="assets", on_delete=models.CASCADE
    )
    tag = models.ManyToManyField(
        "Tag", verbose_name="标签", related_name="assets")
    latest_date = models.DateField(
        verbose_name="更新时间", default=timezone.now, null=True, blank=True
    )
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        verbose_name = "资产表"
        verbose_name_plural = verbose_name
        db_table = "asset"

    def __str__(self):
        return f"{self.tag.all()[0]}-{self.node}-{self.cabinet.name}"


class Server(models.Model):
    #'host_name', 'os_name', 'model_name','physical_count'
    asset = models.OneToOneField(
        Asset,
        related_name="server",
        verbose_name="资产",
        blank=True,
        on_delete=models.CASCADE,
    )
    os_name = models.CharField("操作系统", max_length=520)
    manager_id = models.GenericIPAddressField(
        verbose_name="IP地址", protocol="both", default="", null=True
    )
    machine = models.CharField("系统架构", max_length=520)
    host_name = models.CharField("主机名", max_length=520)
    os_version = models.CharField("系统版本", max_length=520)
    kernel = models.CharField("内核信息", max_length=520)
    model_name = models.CharField("cpu名称", max_length=128)
    cpu_type = models.CharField("cpu类型", max_length=128)
    physical_count = models.IntegerField("cpu物理颗数")
    cpu_cores = models.IntegerField("每颗cpu核心数")
    connection = models.ForeignKey(
        "Connection",
        verbose_name="连接信息",
        blank=True,
        null=True,
        related_name="server",
        on_delete=models.CASCADE,
    )
    latest_date = models.DateField(
        verbose_name="更新时间", default=timezone.now, null=True, blank=True
    )
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        verbose_name = "服务器表"
        verbose_name_plural = verbose_name
        db_table = "server"

    def __str__(self):
        return self.host_name


class Memory(models.Model):
    capacity = models.CharField("内存容量", max_length=100, null=True)
    slot = models.CharField("插槽", max_length=128, null=True)
    model = models.CharField("内存类型", max_length=128, null=True)
    speed = models.CharField("速率", max_length=128, null=True)
    manufacturer = models.CharField("内存厂商", max_length=128, null=True)
    sn = models.CharField("产品序列号", max_length=128, null=True)
    server = models.ForeignKey(
        "Server", verbose_name="服务器", related_name="memory", on_delete=models.CASCADE
    )
    latest_date = models.DateField(
        verbose_name="更新时间", default=timezone.now, null=True, blank=True
    )
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        verbose_name = "内存表"
        verbose_name_plural = verbose_name
        db_table = "memory"

    def __str__(self):
        return f"{self.slot}--{self.capacity}"


class Disk(models.Model):

    coreced = models.CharField("强制磁盘容量", max_length=200, null=True)
    pd = models.CharField("接口类型", max_length=10, null=True)
    raw = models.CharField("原始磁盘容量", max_length=200, null=True)
    slot = models.CharField("插槽号", max_length=10, null=True)
    server = models.ForeignKey(
        "Server", verbose_name="服务器", related_name="disk", on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "硬盘表"
        verbose_name_plural = verbose_name
        db_table = "disk"

    def __str__(self):
        return self.slot


class Connection(models.Model):
    user = models.CharField("ssh用户", max_length=64)
    password = models.CharField("连接密码", max_length=1024)
    port = models.PositiveIntegerField(verbose_name="sshd监听端口")
    authed = models.BooleanField(
        default=False, verbose_name="是否认证", help_text="是否建立互信")

    class Meta:
        verbose_name = "服务器连接表"
        verbose_name_plural = verbose_name
        db_table = "connection"

    # def __str__(self):
    #     return "用户:{}".format(self.user)


class InventoryPool(models.Model):
    group = models.CharField(max_length=64)
    server = models.ManyToManyField("Server", related_name="Inventorypool")

    class Meta:
        verbose_name = "主机组"
        verbose_name_plural = verbose_name
        db_table = "Inventorypool"

    def __str__(self):
        return self.group


class Variable2Group(models.Model):
    """
    变量到组的关系表
    """
    key = models.CharField("变量名", max_length=64)
    val = models.CharField("变量值", max_length=512)
    group = models.ForeignKey("InventoryPool",
                              verbose_name="所属组",
                              related_name="inv2vars",
                              on_delete=models.CASCADE,
                              blank=True, null=True)

    class Meta:
        verbose_name = "Ansible 组变量表"
        verbose_name_plural = verbose_name
        db_table = "var_group"

    def __str__(self):
        return "{}:{}={}".format(self.group.group, self.key, self.val)


class Variable2Server(models.Model):
    """
    变量到主机的关系表
    """
    key = models.CharField("变量名", max_length=64, default='')
    val = models.CharField("变量值", max_length=512, default='')
    host = models.ForeignKey("Server",
                             verbose_name="所属主机",
                             related_name="server2vars",
                             on_delete=models.CASCADE,
                             blank=True, null=True)

    class Meta:
        verbose_name = "Ansible 主机变量表"
        verbose_name_plural = verbose_name
        db_table = "var_host"

    def __str__(self):
        return "{}:{}={}".format(self.host.host_name, self.key, self.val)

adminIE/Cabinet/views.py
from django.shortcuts import render

# Create your views here.



from django.middleware.csrf import CsrfViewMiddleware

adminIE/cmdb/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from .page import StandardResultsSetPagination
from rest_framework import viewsets
from .models import Asset, IDC, Cabinet, Server, Memory, Disk, SysUsers
from .serializers import (
    AssetSerializer,
    IDCSerializer,
    ServerSerializer,
    SysUsersSerializer,
    MemorySerializer,
    DiskSerializer,
    CabinetSerializer,
)

# Create your views here.
from rest_framework import generics
from rest_framework import filters
from django.views.generic import ListView

from pure_pagination.mixins import PaginationMixin
from django_filters.rest_framework import DjangoFilterBackend


class AssetListView(PaginationMixin, ListView):
    paginate_by = 10
    object = Asset
    model = Asset
    context_object_name = "assetList"
    template_name = "cmdb/asset-list-temp.html"


class AssetDetail_temp(DetailView):
    model = Asset
    context_object_name = "asset"

    def get_template_names(self):
        names = []
        type_asset = self.object.get_device_type_id_display()
        if type_asset == "服务器":
            names.insert(0, "cmdb/asset-detail.html")
        elif type_asset == "路由器":
            names.insert(0, "cmdb/router-detail.html")
        elif type_asset == "交换机":
            names.insert(0, "cmdb/switch-detail.html")

        return names

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # print(context)
        asset = context["asset"]
        type_map = {"服务器": "server", "路由器": "router", "交换机": "switch"}
        asset_type = asset.get_device_type_id_display()
        type_obj = type_map.get(asset_type)
        context[type_obj] = getattr(asset, type_obj)
        # context["m"]
        server = context[type_obj]
        context["memory"] = getattr(server, "memory").all()
        # print(context["memory"])
        context["disk"] = getattr(server, "disk").all()
        print(context)
        return context


class AssetViewSet(viewsets.ModelViewSet):
    queryset = Asset.objects.all()
    serializer_class = AssetSerializer
    pagination_class = StandardResultsSetPagination
    filter_backends = [
        DjangoFilterBackend,
        # filters.DjangoFilterBackend,
        filters.SearchFilter,
        # filters.OrderingFilter,
    ]
    filterset_fields = ["device_type_id", "cabinet"]
    search_fields = ["device_type_id", "cabinet"]


class IDCViewSet(viewsets.ModelViewSet):
    queryset = IDC.objects.all()
    serializer_class = IDCSerializer
    pagination_class = StandardResultsSetPagination


class SysUsersViewSet(viewsets.ModelViewSet):
    queryset = SysUsers.objects.all()
    serializer_class = SysUsersSerializer
    pagination_class = StandardResultsSetPagination


class ServerViewSet(viewsets.ModelViewSet):
    queryset = Server.objects.all()
    serializer_class = ServerSerializer
    pagination_class = StandardResultsSetPagination


class MemoryViewSet(viewsets.ModelViewSet):
    queryset = Memory.objects.all()
    serializer_class = MemorySerializer
    pagination_class = StandardResultsSetPagination


class DiskViewSet(viewsets.ModelViewSet):
    queryset = Disk.objects.all()
    serializer_class = DiskSerializer
    pagination_class = StandardResultsSetPagination


class AssetDetail(DetailView):
    model = Asset
    context_object_name = "asset"
    template_name = "detail.html"


class CabinetViewSet(viewsets.ModelViewSet):
    queryset = Cabinet.objects.all()
    serializer_class = CabinetSerializer
    pagination_class = StandardResultsSetPagination


from .models import TreeNode
from .serializers import TreeNodeSerializer


class TreeNodeViewSet(viewsets.ModelViewSet):
    queryset = TreeNode.objects.filter(node_upstream=None)
    serializer_class = TreeNodeSerializer


class ServerListView(ListView):
    template_name = "cmdb/asset-detail.html"
    context_object_name = "servers"

    def get_queryset(self):
        node_id = self.request.GET.get("node_id")
        if node_id:
            queryset = Server.objects.filter(asset__node__id=node_id)
        else:
            queryset = Server.objects.all()
        return queryset


class ServerDetailView(DetailView):
    model = Server
    context_object_name = "server"
    template_name = "cmdb/asset-detail.html"

adminIE/templates/cmdb/asset-detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      资产详情
    </h1>

  </section>

  <!-- Main content -->
  <section class="content">

    <div class="row">
      <div class="col-md-2">

        <!-- Profile Image -->
        <div class="box box-primary">
          <div class="box-body box-profile">
            <img class="profile-user-img img-responsive img-circle" src="{% static 'images/ibm.png' %}"
              alt="User profile picture">
            <h2 class="profile-username text-center">{{ asset.host_name }}</h2>



            <ul class="list-group list-group-unbordered">
              <li class="list-group-item">
                <a class="pull-right">{{ asset.get_device_type_id_display }}</a>
                <b>资产类型</b>
              </li>
              <li class="list-group-item">
                <b>状态 </b> <span
                  class=" pull-right label label-success">{{ server.asset.get_device_status_id_display }}</span>
              </li>
              <li class="list-group-item">
                <b>IP 地址</b> <a class="pull-right">10.0.122.156</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- /.col -->
      <div class="col-md-9">
        <div class="nav-tabs-custom">
          <ul class="nav nav-tabs">
            <li class="active"><a href="#activity" data-toggle="tab">服务器信息</a></li>
            <li><a href="#disk" data-toggle="tab">硬盘信息</a></li>
            <li><a href="#memory" data-toggle="tab">内存信息</a></li>
          </ul>
          <div class="tab-content">
            <div class="active tab-pane" id="activity">
              <!-- Post -->
              <div class="post">
                <ul class="list-group list-group-unbordered">
                  <li class="list-group-item">
                    <b>操作系统</b>
                    <span class="pull-right label label-danger">{{ server.os_name }}</span>
                  </li>
                  <li class="list-group-item">
                    <b>CPU 核心 </b> <span class=" pull-right label label-success">{{ server.physical_count }}</span>
                  </li>
                  <li class="list-group-item">
                    <b>所属机柜</b> <span class="pull-right label label-info">{{ asset.cabinet }}</span>
                  </li>
                  <li class="list-group-item">
                    <b>创建时间</b> <span class="pull-right label label-info">{{ asset.create_at }}</span>
                  </li>
                  <li class="list-group-item">
                    <b>更新时间</b> <span class="pull-right label label-info">{{ asset.latest_date }}</span>
                  </li>
                </ul>
              </div>
            </div>
            <div class="tab-pane" id="disk">
              {% for item in disk  %}
                <ul class="list-group list-group-unbordered">
                  <li class="list-group-item">
                    <b>强制磁盘容量</b>
                    <span class="pull-right label label-danger">{{ item.coreced }}</span>
                  </li>
                  <li class="list-group-item">
                    <b>接口类型 </b> <span class=" pull-right label label-success">{{ item.pd }}</span>
                  </li>
                  <li class="list-group-item">
                    <b>原始磁盘容量</b> <span class="pull-right label label-info">{{ item.raw }}</span>
                  </li>
                  <li class="list-group-item">
                    <b>插槽号</b> <span class="pull-right label label-info">{{ item.slot }}</span>
                  </li>
                  <li class="list-group-item">
                    <b>服务器</b> <span class="pull-right label label-info">{{ item.server }}</span>
                  </li>
                
                </ul>
                {% endfor  %}
              </div>



            <div class="tab-pane" id="memory">
              {% for item in  memory %}
              <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>内存容量</b>
                  <span class="pull-right label label-danger">{{ item.capacity }}</span>
                </li>
                <li class="list-group-item">
                  <b>插槽 </b> <span class=" pull-right label label-success">{{ item.slot }}</span>
                </li>
                <li class="list-group-item">
                  <b>内存类型</b> <span class="pull-right label label-info">{{ item.model }}</span>
                </li>
                <li class="list-group-item">
                  <b>速率</b> <span class="pull-right label label-info">{{ item.speed }}</span>
                </li>
                <li class="list-group-item">
                  <b>内存厂商</b> <span class="pull-right label label-info">{{ item.manufacturer }}</span>
                </li>
                <li class="list-group-item">
                  <b>产品序列号</b> <span class="pull-right label label-info">{{ item.sn }}</span>
                </li>
                <li class="list-group-item">
                  <b>更新时间</b> <span class="pull-right label label-info">{{ item.latest_date }}</span>
                </li>
              </ul>
              {% endfor %}
            </div>
            <!-- /.tab-pane -->
          </div>
          <!-- /.tab-content -->
        </div>
        <!-- /.nav-tabs-custom -->
      </div>
      <div class="col-md-9">
  
        <!-- /.nav-tabs-custom -->
      </div>
    </div>
    <!-- /.row -->

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->
{% endblock %}

adminIE/templates/cmdb/asset-list-temp.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block content %}

<div class="row">
    <div class="row" id="app">
        <div class="col-md-12">
            <div class="box" >
                <div class="box-header">
    
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table table-bordered table-hover dataTable" role="grid"
                                    aria-describedby="example2_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1"
                                                colspan="1" aria-sort="ascending"
                                                aria-label="Rendering engine: activate to sort column descending">
                                                ID</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                                colspan="1" aria-label="Browser: activate to sort column ascending">
                                                资产名</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                                colspan="1" aria-label="Platform(s): activate to sort column ascending">
                                                类型</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                                colspan="1"
                                                aria-label="Engine version: activate to sort column ascending">
                                                状态</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                                colspan="1" aria-label="CSS grade: activate to sort column ascending">
                                                所属机柜</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                                colspan="1" aria-label="CSS grade: activate to sort column ascending">
                                                更新时间</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                                colspan="1" aria-label="CSS grade: activate to sort column ascending">
                                                创建时间</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1"
                                                colspan="1" aria-label="CSS grade: activate to sort column ascending">
                                                更多</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in assetList%}
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">{{ item.id }}</td>
                                            <td>{{ item.server.host_name }}</td>
                                            <td>{{ item.get_device_type_id_display }}</td>
                                            <td>{{ item.get_device_status_id_display }}</td>
                                            <td>{{ item.cabinet.name }}</td>
                                            <td>{{ item.latest_date }}</td>
                                            <td>{{ item.create_at }}</td>
                                            <td><a href="{% url 'cmdb:detail_temp' item.id %}">详情</a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th rowspan="1" colspan="1">ID</th>
                                            <th rowspan="1" colspan="1">资产名</th>
                                            <th rowspan="1" colspan="1">类型</th>
                                            <th rowspan="1" colspan="1">状态</th>
                                            <th rowspan="1" colspan="1">所属机柜</th>
                                            <th rowspan="1" colspan="1">更新时间</th>
                                            <th rowspan="1" colspan="1">创建时间</th>
                                            <th rowspan="1" colspan="1">点击获取详情</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        <div class="row">

                            <div class="col-sm-7">
                                    <center>
                                <div class="dataTables_paginate paging_simple_numbers">
                                    
                                    <ul class="pagination">

                                        <li class="paginate_button previous">
                                            {% if page_obj.has_previous %}
                                            <a
                                                href="?{{ page_obj.previous_page_number.querystring }}">{% trans "previous" %}</a>
                                            {% else %}
                                            <span class="disabled prev">&lsaquo;&lsaquo; {% trans "previous" %}</span>
                                            {% endif %}
                                        </li>
                                        <li>
                                            {% for page in page_obj.pages %}
                                            {% if page %}
                                            {% ifequal page page_obj.number %}
                                            <span class="current page">{{ page }}</span>
                                            {% else %}
                                            <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                                            {% endifequal %}
                                            {% else %}
                                            ...
                                            {% endif %}
                                            {% endfor %}
                                        </li>

                                        <li class="paginate_button next">
                                            {% if page_obj.has_next %}
                                            <a href="?{{ page_obj.next_page_number.querystring }}">{% trans "next" %}
                                                &rsaquo;&rsaquo;</a>
                                            {% else %}
                                            <span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span>
                                            {% endif %}

                                        </li>
                                    </ul>
                                
                                </div>
                            </center>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}

{% endblock %}

adminIE/templates/cmdb/detail.html
{% extends 'base.html'  %}
{% block content %}
<!-- {% for item in assets.server.all %}
    <div>{{ item.name }}</div> -->
    <h1>rourou</h1>
{% endfor %}
{% endblock %}